#!/usr/bin/env node
'use strict';

const path            = require('path');
const dotenv          = require('dotenv');
const compareVersions = require('node-version-compare');

// load environment variables
loadEnv();

const configuration    = require('./config');
const NODE_VERSION_CUR = process.versions.node;
const NODE_VERSION_MIN = '8.0.0';

global.getConfig = getConfig;

//setting time zone
process.env.TZ = 'Asia/Tokyo';

checkNodeVersion(NODE_VERSION_MIN);

require('./src/commands/redmime');

//
// ─── FUNCTIONS ──────────────────────────────────────────────────────────────────
//

function loadEnv () {
    dotenv.config({
        path: path.join(__dirname, '.env')
    });
}

function getConfig (name) {
    const config = configuration[name];
    if (config === undefined)
        throw new Error(`config ${name} is not found`);
    return config;
}

function checkNodeVersion (minVer) {
    const notCompatible = compareVersions(NODE_VERSION_CUR, minVer) === -1;
    if (notCompatible) {
        console.error(`Required NodeJS minimum version: ${minVer}`);
        process.exit(1);
    }
}
